[tool.ruff]
select = ["E", "W", "F", "D", "I", "C"]
ignore = ["D100", "D401", "D406", "D407"]

fixable = ["ALL"]
unfixable = []

line-length = 120

exclude = [".git"]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py38"

[tool.black]
line-length = 120
